package ca.sait.cprg311.WarAtSea.util.Event;

public enum EventType
{
	MOUSE_CLICK,
	KEY_PRESS,
	ATTRIBUTE_CHANGED,
	NETWORK_MESSAGE_RECIEVED,
	STATE_CHANGE,
	CHAT_MESSAGE_RECIEVED,
	CHAT_MESSAGE_SEND,
	GAME_ACTION_REQUEST,
	GAME_ACTION_RESPONSE,
	SHIP_REPOSITIONED,
	GAME_ACTION_PLAYER_READY,
	GAME_ACTION_PLAYER_TURN,
	MISSILE_TARGET_REACHED,
	GAME_SYNC
}
