package ca.sait.cprg311.WarAtSea.util;

public enum ControlNetworkMessageCommand
{
	NO_COMMAND,
	MATCHMAKING_RESTARTING,
	MATCHMAKING_QUIT,
	MATCHMAKING_TERMINATED,
	MATCHMAKING_FOUND,
	CLIENT_ID_REQUEST,
	CLIENT_ID_RESPONSE,
	CONNECTION_INIT,
	GAME_SYNC
}
