package ca.sait.cprg311.WarAtSea.Client;

/**
 * Enum Description: An enumeration of the available block types that a GameGrid element may have.
 * @author Jory Vardas
 * @version 1.0
 */
public enum GameGridBlockType
{
	INVALID,
	WATER_MISSED,
	WATER,
	WATER_FOG,
	AIRCRAFT_CARRIER_SEC_1,
	AIRCRAFT_CARRIER_SEC_2,
	AIRCRAFT_CARRIER_SEC_3,
	AIRCRAFT_CARRIER_SEC_4,
	AIRCRAFT_CARRIER_SEC_5,
	BATTLESHIP_SEC_1,
	BATTLESHIP_SEC_2,
	BATTLESHIP_SEC_3,
	BATTLESHIP_SEC_4,
	CRUISER_SEC_1,
	CRUISER_SEC_2,
	CRUISER_SEC_3,
	SUBMARINE_SEC_1,
	SUBMARINE_SEC_2,
	SUBMARINE_SEC_3,
	DESTROYER_SEC_1,
	DESTROYER_SEC_2,
	DESTROYED_AIRCRAFT_CARRIER_SEC_1,
	DESTROYED_AIRCRAFT_CARRIER_SEC_2,
	DESTROYED_AIRCRAFT_CARRIER_SEC_3,
	DESTROYED_AIRCRAFT_CARRIER_SEC_4,
	DESTROYED_AIRCRAFT_CARRIER_SEC_5,
	DESTROYED_BATTLESHIP_SEC_1,
	DESTROYED_BATTLESHIP_SEC_2,
	DESTROYED_BATTLESHIP_SEC_3,
	DESTROYED_BATTLESHIP_SEC_4,
	DESTROYED_CRUISER_SEC_1,
	DESTROYED_CRUISER_SEC_2,
	DESTROYED_CRUISER_SEC_3,
	DESTROYED_SUBMARINE_SEC_1,
	DESTROYED_SUBMARINE_SEC_2,
	DESTROYED_SUBMARINE_SEC_3,
	DESTROYED_DESTROYER_SEC_1,
	DESTROYED_DESTROYER_SEC_2,
}
